import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>wow</title>
      </head>
      <body>
        <header className="bg-white text-black text-xl font-bold p-3 border-b-2">
          <p>Hi I am in src/app/layout.tsx</p>
          <p>In layout.tsx you can add query, contextApi, navbar, footer... etc</p>
          <div className="p-3 bg-red-100 rounded space-x-5">
            <Link href="/" className="p-3 bg-red-300 rounded-full">
              home
            </Link>
            <Link href="/intro" className="p-3 bg-red-300 rounded-full">
              intro
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
