import './globals.css';
import Nav from './components/nav/Nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>OPENER</title>
      </head>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
